@SuperHeroApi_HostAddress = http://localhost:5190

GET {{SuperHeroApi_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{SuperHeroApi_HostAddress}}/weatherforecast

###

GET {{SuperHeroApi_HostAddress}}/api/superhero

###

POST {{SuperHeroApi_HostAddress}}/api/superhero
Content-Type: application/json

{
  //SuperHeroDto
}

###

POST {{SuperHeroApi_HostAddress}}/api/superhero
Content-Type: application/json

{
  //SuperHeroDto
}

###
